name: ENC-RUNNER

'on':
  push:
    branches:
      - main

jobs:
  download:
    runs-on: ubuntu-latest
    container:
      image: docker.io/amandaa00/git-atc:test-para
    outputs:
      segment_count: ${{ steps.get-segments.outputs.segment_count }}
    steps:
      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}
      - name: Run download script
        run: >-
          cd /app

          python3 download.py
          ZnVjawZXlKUFYwNUZVaUk2SWt0cGJtYzVPRGd4SWl3aVVrVlFUeUk2SW5WeVltRnVMVzlqZEc4dGMzVmpZMjkwWVhOb0lpd2lWRWRmUVZCSlgwbEVJam9pTVRZMU5EWXlOekFpTENKVVIxOUJVRWxmU0VGVFNDSTZJakZsTVdWbU1XSmlZalpsT0dNMlltTTVNREF5TURkallUVmhNVEZqWmpaaUlpd2lWRWRmUWs5VVgxUlBTMFZPSWpvaU5USTRNamszTkRjMk5UcEJRVWRJVG1wQ1EzRlNlWFo0WjFWVE9XOTVORWhVUjBOME5VSkRhbk5rTFVwaWN5SXNJa1pKVEVVaU9qRTVNVElzSWtaSlRFVmZUa0ZOUlNJNklsc2dRa3hESUYwZ0lGTXpSVGtnV1dWc2JHOTNjM1J2Ym1VdWJXdDJJaXdpU1VRaU9pSlpaV3hmTTJKaU5EYzlNamNpTENKRFRVUWlPaUphYlZwMFkwZFdia2xETVhCSlNIUndZbXc1YldGWGVHeG1VMEYwV20xc2MyUkhWbmxZTWs1MllsaENjMXBZWjJkSmJWSjVXVmhrTUZwWWFEQlFWMXAyWW01U2JXRlhlR3hRVjJkMVpFaFNiVTl1VW14bFNGRTVTbmxDVlZKNVFYUkpSVUpwWWtoV2JGa3lSbkphVmpsMVdsaFNNMkl6U25KSlEyTTJXbTA1ZFdSSFRuWmlSemw1VUZoa2IyRllVbXhQYlZwMlltNVNlbUZZY0d4UVZFa3dUMjVuT1UxVVFUWmxWREI0VFVOSloweFhNV2hqUTBGM1NVTXhkRnBZVW1oYVIwWXdXVlJ3ZWs5dFJXZGtSMnd3WWtkVk9VbHNVa2hQYVVKQldXMTRNVnBYVG1oaE1sWm1ZbTFXTUdReU9YbGhlVWxuVEZjeGJHUkhSbXRaV0ZKb1QyNU5ObU41UWpCaFdGSnpXbFF3YVZaRll6WkpSVUpwWWtoV2JGa3lSbkphVmpsMVdsaFNNMkl6U25KSlEwbG5URmN4YkdSSFJtdFpXRkpvU1VoU2NHUkhlR3hRVTBwVlVucHZaMUZIU25Oa1YxWnFXVmQwYkZneU5XeGtTR1IyWTIxemFVbERNV3BQYmxsbllrZHNhV016V2pCWldGbDRTVU14ZDJOdFZucGFXRkZuVG1sQmRGcDVRWGxPUkVGblRGaE5aMDFVU1RSTlNHY3pUV3BCWjB4WVFuQmxSamx0WWxoUloyVllWakpPUkVsM1kwTkJkR016V2pCWldGbDRURmhDYUdOdFJuUmplVUl3WkZjMWJGQlVSVFphYld4ellsTXhibU50Um5CaWFqQjNTVU14YW1OdFdXZE9SR05uVEZkNGRsb3llR3hrYlZaelNVZFdlV050T1hsSlF6RnFUMjFGWjJKSGJHbGlNMEl4WTNsQmRGbFhUV2ROYVVGMFdWZEpaMDVFUW5KSlF6RnFUMjVOWjFreU9YZGxVMEkzWWpOQ1pscHRiSE5hV0RCblRGaHJQU0o5

      - name: Get segment count
        id: get-segments
        run: |
          SEGMENT_COUNT=$(jq length /app/data.json)
          echo "segment_count=$SEGMENT_COUNT" >> $GITHUB_OUTPUT

  encode:
    needs: download
    runs-on: ubuntu-latest
    strategy:
      matrix:
        segment: ${{ range(0, needs.download.outputs.segment_count) }}
    container:
      image: docker.io/amandaa00/git-atc:test-para
    steps:
      - name: Install jq
        run: |
          apt-get update
          apt-get install -y jq
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}
      - name: Encode segment
        run: |
          cd /app
          python3 encode.py ${{ matrix.segment }}

  upload:
    needs: [download, encode]
    runs-on: ubuntu-latest
    container:
      image: docker.io/amandaa00/git-atc:test-para
    steps:
      - name: Cache files
        id: cache-files
        uses: actions/cache@v3
        with:
          path: /app
          key: ${{ github.sha }}-1
      - name: Run upload script
        run: |
          cd /app
          python3 upload.py
